### PR TITLE
Hotfix: Tensile tag update #1811

### PR DESCRIPTION
**Pull request by aferoz21**
resolves #SWDEV-419897

Summary of proposed changes:
- This PR has the fix to run tensile in gfx1102 products mentioned in the above ticket.

### CODE REVIEW

**Comment by nakajee** [comment]
We have 2 PRs (#1370 and this) for tensile tag update for release-rel-6.0.
Please make sure the final tensile tag update includes both changes.

**Review by TorreZuk — APPROVED** [review]
Coordinate with @rkamd as the other hotfix has a tensile commit as well.

**Review by rkamd — APPROVED** [review]

**Comment by rkamd** [comment]
> Coordinate with @rkamd as the other hotfix has a tensile commit as well.

This PR can be merged first, I will make sure both changes are included while merging #1370 
@aferoz21 , Please let me know if you need help merging this PR.

**Comment by rkamd** [comment]
@aferoz21 , I have merged #1370, the tensile tag update has both changes and currently points to tip of release/rocm-rel-6.0 of Tensile repo.

**Closing this PR**

**Pull request closed without merging**
