### PR TITLE
arcturus HHS tuning hotfix

### PR DESCRIPTION
**Pull request by benjaminulmer**
Fix for SWDEV-373015

Introduces 1 new kernel and 1 new size

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM if extended all pass

**Comment by benjaminulmer** [comment]
Does trtri call gemm? Could this failure be caused by this change?

**Comment by mahmoodw** [comment]
> Does trtri call gemm? Could this failure be caused by this change?

trtri does call gemm, I am not sure how these changes will affect it but probably a good idea to check the kernel being called in the failing test, before and after the changes. (TENSILE_DB=0x8000)

**Comment by benjaminulmer** [comment]
I got my wires crossed. This PR only affects gfx908, so the gfx90a failure is unrelated. I'll put the failure below for posterity


 _/trtri.blas3_tensile/nightly_trtri_f64_c_LU_2016_2016, where GetParam() = { function: "trtri", name: "trtri", category: "nightly", known_bug_platforms: "", alpha: 1.0, alphai: 0.0, beta: 0.0, betai: 0.0, stride_a: 0, stride_b: 0, stride_c: 0, stride_d: 0, stride_x: 0, stride_y: 0, user_allocated_workspace: 0, M: 128, N: 2016, K: 128, KL: 128, KU: 128, lda: 2016, ldb: 0, ldc: 0, ldd: 0, incx: 0, incy: 0, incd: 0, incb: 0, batch_count: 1, iters: 10, cold_iters: 2, algo: 0, solution_index: 0, flags: none, a_type: f64_c, b_type: f64_c, c_type: f64_c, d_type: f64_c, compute_type: f64_c, initialization: "rand_int", arithmetic_check: "invalid", atomics_mode: atomics_allowed, pad: 4096, threads: 0, streams: 0, devices: 
```
The difference between std::real(ta) and std::real(tb) is 1.5987211554602254e-13, which exceeds abs_error, where
std::real(ta) evaluates to -11.212472854293573,
std::real(tb) evaluates to -11.212472854293733, and
abs_error evaluates to 1.5700924586837751e-13.
```

**Review by babakpst — APPROVED** [review]
The changes in the lib logic look good. I could not figure out the relation between this change and the failure.

**Comment by babakpst** [comment]
This PR affects gfx908 only, and all the corresponding gfx908 tests pass. I don't see the failed gfx90a test that Ben mentioned in the comment. Instead, trsm test is failing now. I am locally running tests again.

**Comment by babakpst** [comment]
This PR is ready for merge, and the failed tests are irrelevant to these changes.

**Pull request merged**
