### PR TITLE
Adding system requirements to install documentation

### PR DESCRIPTION
**Pull request by daineAMD**
Currently there doesn't seem to be any documentation on system memory requirements to build rocBLAS. This PR may not be 100% accurate so discussion is welcome on what the requirements _actually_ are.

Andrew mentioned that he was able to successfully build on a Vega20 with 24GB.

### CODE REVIEW

**Comment by TorreZuk** [comment]
@saadrahim wondering if we can in the future flag some PRs as not requiring build or test stages?

**Comment by saadrahim** [comment]
image
We can exclude the docs folder. Does anyone object?

**Comment by TorreZuk** [comment]
Unless there is a documentation pipeline that gets run....

**Comment by daineAMD** [comment]
Changed to 64GB, changed the wording to mention the --logic flag for ./install.sh. Will merge here soon if no one has any other recommendations.

**Pull request merged**
