### PR TITLE
Fix SGEMM TN getsolutions gtest failure

### PR DESCRIPTION
**Pull request by yenong-amd**
resolves # SWDEV-484060

Summary of proposed changes:
- First commit removed unused solutions.
- Second commit added back solutions with tuned sizes assigned to the solutions.
- Third commit removed duplicate sizes. 
Net effect is - some duplicated sizes removed and some tuned sizes updated with new solutions.

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM, get Tensile review pleae

**Comment by TorreZuk** [comment]
@eidenyoshida is this not getting CI?

**Comment by nakajee** [comment]
Why update is more than removing sizes?

**Comment by nakajee** [comment]
> Why update is more than removing sizes?

OK. This includes 3 different commits.
I am OK with the change.

**Comment by nakajee** [comment]
If CI does not work for this branch, please run the test on your local node.

**Comment by vamovsik** [comment]
Fix for https://ontrack-internal.amd.com/browse/SWDEV-484060

**Pull request merged**
