### PR TITLE
use python3 

### PR DESCRIPTION
**Pull request by TorreZuk**
* python3 as Centos8 may not have python without alternatives

### CODE REVIEW

**Comment by TorreZuk** [comment]
It is run as python3 for tensile and we have python3 as a dependency.

**Comment by TorreZuk** [comment]
I said they could just install python2 as python using alternatives but Aditya chose this.

**Comment by pruthvistony** [comment]
The changes look good to me.

**Comment by adilad** [comment]
Will this work for Centos7 ?

**Comment by leekillough** [comment]
On modern Pythons versions, `python` should be a symlink to `python3`. 

I don't see any problems with this change, unless certain platforms require `python` to be used instead of `python3`.

**Comment by TorreZuk** [comment]
>This works on older OSes?
It is run as python3 for tensile and we have python3 as a dependency.
(implied it should work on older ones if tensile does)
> Will this work for Centos7 ?
Passed on our Centos7.

**Pull request merged**
