### PR TITLE
improve trsm tests

### PR DESCRIPTION
**Pull request by amcamd**
resolves # swdev-12710

Summary of proposed changes:
- initialize with L from Cholesky factorization of SPD matrix
-  test error and residual using reference trmm in place of reference trsm
-

### CODE REVIEW

**Comment by b-sumner** [comment]
Won't these large increases let other problems through?  I'd rather better control the input matrices than raise the tolerance so much.

**Comment by kknox** [comment]
@b-sumner  @tingxingdong 
xTRSM is something of a special precision nightmare because of the integrated matrix inversion operation.  I believe Tim tried to cook the input matrices with base2 numbers, but we are still struggling with what appears to be precision problems.

Any other ideas?  We could just test smaller matrices.

**Comment by amcamd** [comment]
I am rewriting the initialization of the matrix. Below is from the new comment in the code

//  Random lower triangular matrix have condition number
//  that grows exponentially with matrix size. Random full
//  matrices have condition that grows linearly with 
//  matrix size. To generate a lower triangular matrix
//  with condition number that grows with matrix size 
//  start with full random matrix A. Calculate B <- A A^T. 
//  Make B strictly diagonal dominant. Next use Cholesky 
//  factorization to calculate L L^T = B. These L factors 
//  should have condition number approximately equal to
//  the condition number of the original matrix.

I will submit the new code. The new code should produce a starting L with better condition number.

**Comment by b-sumner** [comment]
I think limiting the size to the minimum we're sure will test all of the code along with the proposed new matrix calculation should be sufficient.

**Pull request merged**
