### PR TITLE
Search for rocblas_gtest.data in the same directory as rocblas-test

### PR DESCRIPTION
**Pull request by leekillough**
Search for rocblas_gtest.data in the same directory as rocblas-test

### CODE REVIEW

**Comment by leekillough** [comment]
The error message seems fairly clear, that it cannot open rocblas_gtest.data.

This is not a common user error, but more like an internal error which should never happen.

The rocblas_gtest.data file and rocblas-test executable are closely tied together. rocblas-test cannot work without rocbas_gtest.data.

The rocblas-test user does not need to specify the rocblas_gtest.data file, because they didn't have to specify it before refactoring, and the normal Google Tests workflow does not involve supplying data files on the command-line or elsewhere, but simply running an executable.

The -h message is handled by Google Tests.

The opening of the data file needs to occur before the first Google Test is created, which happens at the same time as Google Tests parses the command-line. 

We could defer the opening of the data file until the first time it's actually needed, with a little more logic.

**Comment by leekillough** [comment]
Another change will be posted soon, which defers the opening of the file until it's absolutely required, which allows the Google Tests CLI parsing and other stuff to finish first (so that rocblas-test -h etc. can be printed).

**Comment by gilbertlee-amd** [comment]
Looks good

**Comment by leekillough** [comment]
I verified, by putting a fake filename in the rocblas_gtest_main.cpp file, that rocblas-test -h prints the help message before aborting with the bad filename. (I don't know why Google Tests doesn't immediately exit after printing -h help output.)

**Pull request merged**
