### PR TITLE
trial use of omp in client/common

### PR DESCRIPTION
**Pull request by TorreZuk**
* adds openmp to speed up reference herkx calculations

### CODE REVIEW

**Comment by leekillough** [comment]
#922 has changes to random number generation to allow multiple threads to generate random numbers concurrently, generating independent yet deterministic (based on thread id) sequences.

**Comment by TorreZuk** [comment]
Sure I can produce a time comparision and post shortly, I only verified in the disassembly saw an omp fork.  This is a reference function, no random numbers generated by threads...

Back to Lee's comment  -- presuming your random numbers per thread will likely be sent to either columns or batches it will still result in non-determinism in the input data based on random omp scheduling and total threads available if we parallelize the random data creation process.    #922 has so much in it already not sure if I will decode that part from it.

**Comment by TorreZuk** [comment]
Timing individual cpu reference locally with small data shows openmp is slower (startup overhead)
./rocblas-bench -f herkx -r f32_c --uplo L --transposeA N -n 199 -k 33 --alpha 1.5 --alphai -1 --lda 199 --ldb 199 --beta 1 --ldc 199 -v 1
~ 8 +/- 6 ms (openmp)
~ 0.3 ms (OLD == current non OpenMP reference)
larger data, then it wins and is where the times are much bigger:
./rocblas-bench -f herkx -r f64_c --uplo L --transposeA C -n 1024 -k 1200 --alpha -2 --alphai 0.5 --lda 1200 --ldb 1200 --beta -1 --ldc 1024 -v 1
~ 88 +/- 6 ms (openmp)
~ 540 +/- 10 ms (OLD)

Testing shows improved timing for large tests and slowdown in small tests but cumulative slow down in small tests isn't significant compared to overall test time reductions.

 PR CI tests for ubuntu18 && gfx900

OpenMP
[----------] 144 tests from quick/herkx
[----------] 144 tests from quick/herkx (158 ms total)
[----------] 130 tests from pre_checkin/herkx
[----------] 130 tests from pre_checkin/herkx (1291 ms total)
[----------] 288 tests from quick/herkx_batched
[----------] 288 tests from quick/herkx_batched (107 ms total)

[----------] 258 tests from pre_checkin/herkx_batched
[----------] 258 tests from pre_checkin/herkx_batched (9931 ms total)
[----------] 288 tests from quick/herkx_strided_batched
[----------] 288 tests from quick/herkx_strided_batched (157 ms total)
[----------] 258 tests from pre_checkin/herkx_strided_batched
[----------] 258 tests from pre_checkin/herkx_strided_batched (9269 ms total)

Old
[----------] 144 tests from quick/herkx
[----------] 144 tests from quick/herkx (102 ms total)
[----------] 130 tests from pre_checkin/herkx
[----------] 130 tests from pre_checkin/herkx (1624 ms total)
[----------] 288 tests from quick/herkx_batched
[----------] 288 tests from quick/herkx_batched (117 ms total)

[----------] 258 tests from pre_checkin/herkx_batched
[----------] 258 tests from pre_checkin/herkx_batched (10302 ms total)
[----------] 288 tests from quick/herkx_strided_batched
[----------] 288 tests from quick/herkx_strided_batched (109 ms total)
[----------] 258 tests from pre_checkin/herkx_strided_batched
[----------] 258 tests from pre_checkin/herkx_strided_batched (9373 ms total)



OpenMP
[----------] 64 tests from nightly/herkx
[----------] 64 tests from nightly/herkx (50944 ms total)
[----------] 32 tests from nightly/herkx_batched
[----------] 32 tests from nightly/herkx_batched (54301 ms total)
[----------] 64 tests from nightly/herkx_strided_batched
[----------] 64 tests from nightly/herkx_strided_batched (98800 ms total)

Old
[----------] 64 tests from nightly/herkx
[----------] 64 tests from nightly/herkx (65689 ms total)
[----------] 32 tests from nightly/herkx_batched
[----------] 32 tests from nightly/herkx_batched (58304 ms total)
[----------] 64 tests from nightly/herkx_strided_batched
[----------] 64 tests from nightly/herkx_strided_batched (128473 ms total)

OpenMP
...
258 tests from pre_checkin/herkx_batched (4352 ms total)
64 tests from nightly/herkx_strided_batched (43731 ms total)
[==========] 1526 tests from 9 test cases ran. (98151 ms total)

No OpenMP
...
258 tests from pre_checkin/herkx_strided_batched (3921 ms total)
64 tests from nightly/herkx_strided_batched (70372 ms total)
[==========] 1526 tests from 9 test cases ran. (146722 ms total)

**Comment by leekillough** [comment]
> 
> 
> Sure I can produce a time comparision and post shortly, I only verified in the disassembly saw an omp fork. This is a reference function, no random numbers generated by threads...
> 
> Back to Lee's comment -- presuming your random numbers per thread will likely be sent to either columns or batches it will still result in non-determinism in the input data based on random omp scheduling and total threads available if we parallelize the random data creation process. #922 has so much in it already not sure if I will decode that part from it.

The change was mainly done so that the thread-safe logging tests could be written, where multiple threads generate random data at the same time and output to the same file, and then it is verified that they did not interfere with each other, garbling the output.

In the past I've written random number generators, and to make them thread-safe yet independent, the same random number generator is used in each thread, but its state is thread_local, and its seed (starting state) is a pseudorandom hash of the thread's ID. We cannot avoid nondeterminism caused by a random permutation of thread order, but we can ensure that if the same program is run again with the same number of threads, then as long as its result does not depend on the order in which the threads execute, it will generate the same sequences in thread 0, thread 1, thread 2, etc.

**Comment by TorreZuk** [comment]
Andrew you were right the setup time is significant for a single small data run, but as once those omp worker threads are setup I think the cost is minimal so don't expect we should control omp vs non-omp based on data size and just use them for all cases no matter how small.     I'll go ahead and merge unless someone speaks up shortly as all the rel3.3 failures are unrelated.

**Pull request merged**
