### PR TITLE
Hotfix: fix for aldebaran DGEMM NT mismatch issue

### PR DESCRIPTION
**Pull request by nakajee**
resolves # SWDEV-481147

Summary of proposed changes:
- removed the problematic kernel
- added gtest

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM if tests pass but please add yaml comment as per develop PR commentary.  Needs tensile review before merge.  Thanks!

**Comment by nakajee** [comment]
> LGTM if tests pass but please add yaml comment as per develop PR commentary. Needs tensile review before merge. Thanks!

I just added comment.

**Comment by nakajee** [comment]
Some fails in CI test, but most likely not related to my change.
Do I need more approval for hotfix?
Just from Tensile team is enough?

**Review by babakpst — APPROVED** [review]

**Comment by nakajee** [comment]
@TorreZuk 
I got another approval from Tensile team.
Please let me know if this is good to go or not.
Quick confirmation.
Is release-staging/rocm-rel-6.3 the right branch for this hotfix?

**Comment by TorreZuk** [comment]
Sure squash and merge, target branch is correct.

**Pull request merged**
