### PR TITLE
Virtual env fix

### PR DESCRIPTION
**Pull request by TorreZuk**
This is based off develop branch not 3.0 like the earlier one, just adds dependency to Paul's simplification to use python3 venv.

### CODE REVIEW

**Comment by amdkila** [comment]
I haven't had the chance to test the last commit I made on any other distro except Ubuntu...I'm hoping CI cooperates. I will test it later in the afternoon on CentOS and SLES. The wildcard is used in case if the user has a different python version on their system- unfortunately CentOS and RHEL tie up all Python packages to each Python point release :(

**Comment by amdkila** [comment]
I think we're home free now. Sorry- didn't get around to testing this until about 45 minutes ago. All distros have passed the docker stage and have created the virtual environment

**Comment by TorreZuk** [comment]
No worries.   Not sure but I would have thought the python3-virtualenv is actually the old python module on those platforms that we should now be ignoring in this PR as switching to the venv module as both could exist, quite a messy naming situation.

**Comment by amdkila** [comment]
Yeah, that was my assumption too, but I searched for all pages with venv in their name and found nothing. It appears to be the new one- [this page](https://software.opensuse.org/package/python3-virtualenv) on the openSUSE site gave me a clue that this appears to be the latest python3 virtualenv

**Comment by TorreZuk** [comment]
virtualenv lives on a standalone module and venv should be included as a standard package in many python3 since 3.3, unfortunately venv is separated out in some distributions.   The virtualenv package shouldn't be needed but won't hurt either as Paul's code explicitly invokes venv.   The distros that don't have python3*-venv probably don't need anything beyond python3* unless they are really trying to annoy us which might be the case :-)

**Comment by TorreZuk** [comment]
Still need a review @mahmoodw ?  Will wait for some more tests.   @amdkila  are you done with package adjustments for now?

**Comment by amdkila** [comment]
> Still need a review @mahmoodw ? Will wait for some more tests. @amdkila are you done with package adjustments for now?

Yes I am

**Pull request merged**
