### PR TITLE
Add missing __device__ label

### PR DESCRIPTION
**Pull request by amdkila**

### CODE REVIEW

**Comment by leekillough** [comment]
> 
> 
> My fault for missing this, thanks Akila.

How did it even compile, though? :) Was there a `__host__` fallback function?

**Comment by amdkila** [comment]
The failure is infrastructure-related (laggy file system). Another job should fail as rack 88 lost connection. If any 1 of these passes the compile stage, I'll merge this in.

**Comment by aaronenyeshi** [comment]
> > My fault for missing this, thanks Akila.
> 
> How did it even compile, though? :) Was there a `__host__` fallback function?

HIP-Clang is more strict, whereas HCC will allow `__device__` to call `__host__` functions, since it sets all device callees as device too.

**Comment by leekillough** [comment]
> 
> 
> > > My fault for missing this, thanks Akila.
> > 
> > 
> > How did it even compile, though? :) Was there a `__host__` fallback function?
> 
> HIP-Clang is more strict, whereas HCC will allow `__device__` to call `__host__` functions, since it sets all device callees as device too.

Ah, got it.

**Pull request merged**
